name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  pull_request:
    branches:
      - main  # Optional: Triggers on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettify

      - name: Lint code
        run: npm run lint

      - name: Run placeholder tests
        run: npm run test

      - name: Build the frontend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only runs if build job passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $VERCEL_API_TOKEN" \
            "https://api.vercel.com/v1/integrations/deploy/${{ secrets.VERCEL_PROJECT_ID }}" \
            -d '{}'
